###################################
#  SMP PIPORLANDIA 2 CORE Plugin  #
###################################


# Eventos
events:
  # Evento de alga
  alga: false

# Propiedades del teletransportador del Limbo
limbo:
  # Ubicación de salida del teletransportador.
  world:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0
  # Ubicación del teletransportador.
  portal:
    x: 0
    y: 0
    z: 0